title: Learn about pitch, roll and yaw
hero_image: images/banner.png
description: Learn the difference between pitch, roll and yaw and what the measurements are used for.
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 # possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: ""
site_areas:
steps:
  - title: Introduction
